version: "3"

services:
  wg:
    build: .
    image: wg-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SESSION_SECRET=$SESSION_SECRET
      - WGUI_USERNAME=$WGUI_USERNAME
      - WGUI_PASSWORD=$WGUI_PASSWORD
      - WGUI_MANAGE_START=$WGUI_MANAGE_START
      - WGUI_MANAGE_RESTART=$WGUI_MANAGE_RESTART
      - WGUI_API_KEY=$WGUI_API_KEY
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
